### ISSUE TITLE
Feature request: update the stackset template file and trigger an update for all stackset instances

### ISSUE THREAD

**Issue by tomiszili** [aws-samples/aws-cloudformation-stackset-orchestration#2]
Hi!

An update option for the stackset template file should be helpful, and an automatic update operation for all corresponding stackset instances.

Thanks!

**Comment by sebiwi** [comment]
Hello @tomiszili,

I am having a hard time understanding what you want to achieve. Can you please explain your intended workflow?

**Comment by tomiszili** [comment]
Hi @sebiwi,

Sorry for the unclear description.
I simply want an automatic update for all existing instance in a stackset when a new version of a template file uploaded by theedit menu in a stackset.

**Comment by tomiszili** [comment]
Hi!

To be more specific i want to handle the template file of the stackset in the yaml config, as follows:
```
---
account: '123456789876'
stacksets:
- name: vpc
  templateURL: <s3 URL for the (e.g.: VPC) stackset template object>
parameters:
  CidrBlock: '10.0.0.0/24'
  EnableDnsHostnames: "true"
```
So if the stackset itself not exists the orchestrator will be create with the specified template URL, or if the stackset exists the orchestrator will updates the existing template with the URL specified in the config.yaml file.
